### ISSUE TITLE
Create "about us" page

### ISSUE THREAD

**Issue by uxforgood** [flexion/10x-website#10]
# Scenario
User can learn about who 10x is

# Acceptance Criteria 
- [ ] User can learn about who 10x is

# Tasks
- [ ] Write
- [ ] Design
- [ ] Develop

# Definition of Done

## Product Owner
- [ ] Acceptance criteria is met

## UX
- [ ] Business test scenarios to meet all acceptance criteria are
- [ ] Usability is validated on desktop and mobile devices
- [ ] Wiki / documentation is updated (if applicable)

## Engineering

- [ ] Automated test scripts are written
- [ ] New screens are added to pa11y scripts
- [ ] Site can be navigated with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html
- [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs are fully updated
- [ ] UI is touch optimized and responsive 
- [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
- [ ] Code is refactored for clarity and to remove any known technical debt
- [ ] Deployed to the dev environment
- [ ] Deployed to the stage environment
