### ISSUE TITLE
Conduct usability test to determine if we're displaying the right information on summary page

### ISSUE THREAD

**Issue by uxforgood** [flexion/10x-website#11]
# Scenario
Team conducts informal usability testing to validate usability and usefulness of the new project summary and detail pages. 

# Acceptance Criteria 
- [x] Team has actionable insights to implement from users about the project summary and detail page. 

# Tasks
- [x] Identify participants
- [x] Schedule sessions
- [x] Write questions
- [x] Conduct sessions
- [x] Make recommendations based on feedback

# Definition of Done

## Product Owner
- [ ] Acceptance criteria is met
