### ISSUE TITLE
Project Detail Page: Eligibility APIs Initiative

### ISSUE THREAD

**Issue by maomeara63** [flexion/10x-website#19]
## Acceptance Criteria
- [ ] User can view information on project

## Tasks
- [ ] Project written using [template](https://docs.google.com/document/d/1UEdxhlFKSPq8YEko-6qQQAhsAQhTKyFqgjvOTbD5Mzw/edit?usp=sharing)
- [ ] Copy reviewed for voice and tone, style, completeness
- [ ] Tagging reviewed for consistency
- [ ] Content uploaded into Projects content type

## Definition of Done
- [ ] Acceptance criteria is met
- [ ] Content and design are reviewed to ensure they meet persona needs
- [ ] Content is viewed and tested after being loaded into Projects content type
