### ISSUE TITLE
Project Detail Page: A Guide to the PRA

### ISSUE THREAD

**Issue by maomeara63** [flexion/10x-website#24]
## Acceptance Criteria
- [ ] User can view information on project

## Tasks
- [ ] Project written using [template](https://docs.google.com/document/d/1UEdxhlFKSPq8YEko-6qQQAhsAQhTKyFqgjvOTbD5Mzw/edit?usp=sharing)
- [ ] Copy reviewed for voice and tone, style, completeness
- [ ] Tagging reviewed for consistency
- [ ] Content uploaded into Projects content type

# Definition of Done

## Product Owner
- [ ] Acceptance criteria is met

## UX
- [ ] Content and design are reviewed to ensure they meet persona needs
- [ ] Business test scenarios to meet all acceptance criteria are
- [ ] Usability is validated on desktop and mobile devices
- [ ] Wiki / documentation is updated (if applicable)

## Engineering

- [ ] Automated test scripts are written
- [ ] New screens are added to pa11y scripts
- [ ] Site can be navigated with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html
- [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs are fully updated
- [ ] UI is touch optimized and responsive 
- [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
- [ ] Code is refactored for clarity and to remove any known technical debt
- [ ] Deployed to the dev environment
- [ ] Deployed to the stage environment
