### ISSUE TITLE
Designing Success Page (As a user, I want to learn about 10x's investment strategy)

### ISSUE THREAD

**Issue by maomeara63** [flexion/10x-website#42]
# Scenario
User can learn about 10x's investment strategy

# Acceptance Criteria 
-User can learn about 10x investment strategy
-Projects are ordered in a structured manner

# Tasks
- [ ] Content @maomeara63 
- [ ] Develop

# Definition of Done

## Product Owner
- [ ] Acceptance criteria is met

## UX
- [ ] Content and design are reviewed to ensure they meet persona needs
- [ ] Business test scenarios to meet all acceptance criteria are
- [ ] Usability is validated on desktop and mobile devices
- [ ] Wiki / documentation is updated (if applicable)

## Engineering

- [ ] Automated test scripts are written
- [ ] New screens are added to pa11y scripts
- [ ] Site can be navigated with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html
- [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs are fully updated
- [ ] UI is touch optimized and responsive 
- [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
- [ ] Code is refactored for clarity and to remove any known technical debt
- [ ] Deployed to the dev environment
- [ ] Deployed to the stage environment
