### ISSUE TITLE
Refactor existing site components in React

### ISSUE THREAD

**Issue by uxforgood** [flexion/10x-website#6]
# Scenario
The existing site should be refactored so that its components are built in React. This will make shifting to the new design much easier for 2.0. 

# Acceptance Criteria 
- [x] All existing website components are built in React

# Tasks
- [x] Refactor Header Components
- [x] Refactor Navigation Component & Logic
- [x] Refactor Footer Components
- [x] Move homepage
- [x] Move about
- [x] Move send us idea
- [x] Move process
- [x] Move projects
- [x] Move privacy policy
  

# Definition of Done

## Product Owner
- [x] Acceptance criteria is met

## UX
- [x] Usability is validated on desktop and mobile devices (matches previous design)

## Engineering

- [x] Automated test scripts are written
- [x] New screens are added to pa11y scripts
- [x] Site can be navigated with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html
- [x] READMEs, other appropriate docs, JSDocs and swagger/APIs are fully updated
- [x] UI is touch optimized and responsive 
- [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
- [x] Code is refactored for clarity and to remove any known technical debt
- [x] Deployed to the dev environment
- [x] Deployed to the stage environment
