### ISSUE TITLE
Create project portfolio page (existing design)

### ISSUE THREAD

**Issue by uxforgood** [flexion/10x-website#7]
# Scenario
Users can navigate to a place to see summaries of projects that 10x is working on. 

# Acceptance Criteria 
- [x] User can navigate to a place to see project summaries 
- [x] User can view 6-10 project summaries 

# Tasks
- [x] Create IA for project summary page (where does it live in existing site?) - @kimschulke 
- [x] Select 6-10 projects to write about - @maomeara63 
- [x] Research selected projects (read reports, review presentations, etc) 
- [x] Write summaries for selected projects
- [x] Design project summary page using existing 10x branding - @npage123 
- [x] Build Project CMS config - @plummer-flex 
- [x] Create State Module for Projects - @plummer-flex 
- [x] Create routing for Projects Landing page - @plummer-flex 
- [x] Create project card component - @plummer-flex 
- [x] Upload the content into the Projects content type

# Definition of Done

## Product Owner
- [x] Acceptance criteria is met

## UX
- [x]  Content and design are reviewed to ensure they meet persona needs
- [x] Business test scenarios to meet all acceptance criteria are
- [x] Usability is validated on desktop and mobile devices
- [x] Wiki / documentation is updated (if applicable)

## Engineering

- [x] Automated test scripts are written
- [x] New screens are added to pa11y scripts
- [x] Site can be navigated with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html
- [x] READMEs, other appropriate docs, JSDocs and swagger/APIs are fully updated
- [x] UI is touch optimized and responsive 
- [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
- [x] Code is refactored for clarity and to remove any known technical debt
- [x] Deployed to the dev environment
- [x] Deployed to the stage environment

**Comment by uxforgood** [comment]
# Business test scenarios

**Comment by npage123** [comment]
@willcahoe A link to the updated project summary page is below. When you and Nico (didn't see his name in here to add) get a chance, please take a look and provide any feedback.
A few notes:

1. Does not include finalized content but has placeholders for final content. Content will be finalized in the google doc. 
2. Page 2 of the PDF shows how projects would look in a mobile view.
3. Pages 3-5 show hover, down, and up button states which follows what exists currently.
4. Selecting a project will take the user to it's github page until project detail pages are created.

[https://app.zenhub.com/files/294195953/07b8bd42-c8c2-42e8-a97f-9f8fa615e873/download](https://app.zenhub.com/files/294195953/07b8bd42-c8c2-42e8-a97f-9f8fa615e873/download)

CC: @plummer-flex @uxforgood @kimschulke @maomeara63 @sstatz

**Comment by kimschulke** [comment]
### **Test Cases**

**User clicks Our Projects on homepage**

- [ ] On click color box displays around Our Projects

- [ ] On release of click, color box changes color

**User views Our Projects Page**

- [ ] Content includes: Our Projects with brief intro sentence at top, 10x square logo, About Our Projects, Projects

**User views Projects section of Projects Page**

- [ ] Projects display within boxes

- [ ] Each project box includes Title in red/orange, goal statement, type of project, paragraph description, tags, phase timeline, explanation of timeline
