### ISSUE TITLE
Create newly branded homepage

### ISSUE THREAD

**Issue by uxforgood** [flexion/10x-website#9]
# Scenario
User can navigate to a new homepage that explains who 10x is. 

# Acceptance Criteria 
- [ ] User can navigate to a homepage that explains who 10x is
- [ ] User can see that 10x is associated with GSA

# Tasks
- [ ] Set up new theme design (2.0) in Federalist 

# Definition of Done

## Product Owner
- [ ] Acceptance criteria is met

## UX
- [ ] Business test scenarios to meet all acceptance criteria are
- [ ] Usability is validated on desktop and mobile devices
- [ ] Wiki / documentation is updated (if applicable)

## Engineering

- [ ] Automated test scripts are written
- [ ] New screens are added to pa11y scripts
- [ ] Site can be navigated with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html
- [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs are fully updated
- [ ] UI is touch optimized and responsive 
- [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
- [ ] Code is refactored for clarity and to remove any known technical debt
- [ ] Deployed to the dev environment
- [ ] Deployed to the stage environment

**Comment by npage123** [comment]
@willcahoe and Nico, here's the updated homepage. We've made some changes which include:

1. Lightening up the background gradient
2. Created a new brush transition between the blue and purple at the top
3. Styling of the deadline box (still in progress)
4. Styling of the funded stat
5. Added the 'What's going on right now' featured area with four unique templates that can be dynamic
6. Added the callout that includes projects that started as 10x submissions
7. Added a placeholder for the footer

Once again, we welcome the feedback.

![Homepage-3.1.5.jpg](https://images.zenhubusercontent.com/58f7701e51aa2c30577bd12c/f0e19974-bfc3-416a-bf6d-1f6586c211a5)
